services:
  backend:
    image: parkseheon/a603-backend
    container_name: coursefree
    environment:
      USE_PROFILE: ${USE_PROFILE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 8081:8081
    networks:
      - coursefree

networks:
  coursefree:
    external: true

