// 나중에 프론트, 백 추가
services:
  bigdata:
    image: parkseheon/a603-bigdata
    container_name: coursefree-bigdata
    ports:
      - 8000:8000
    networks:
      - coursefree

networks:
  coursefree:
    external: true

